# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from control_plane import agent_msg_pb2 as agent__msg__pb2


class AgentLinkStub(object):
    """`service` is used to define methods for gRPC services in a fixed format, similar to defining
    an interface in Golang
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Simple = channel.unary_unary(
                '/agnet_msg.AgentLink/Simple',
                request_serializer=agent__msg__pb2.AgentMsg.SerializeToString,
                response_deserializer=agent__msg__pb2.AgentMsg.FromString,
                )


class AgentLinkServicer(object):
    """`service` is used to define methods for gRPC services in a fixed format, similar to defining
    an interface in Golang
    """

    def Simple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentLinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Simple': grpc.unary_unary_rpc_method_handler(
                    servicer.Simple,
                    request_deserializer=agent__msg__pb2.AgentMsg.FromString,
                    response_serializer=agent__msg__pb2.AgentMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agnet_msg.AgentLink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentLink(object):
    """`service` is used to define methods for gRPC services in a fixed format, similar to defining
    an interface in Golang
    """

    @staticmethod
    def Simple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agnet_msg.AgentLink/Simple',
            agent__msg__pb2.AgentMsg.SerializeToString,
            agent__msg__pb2.AgentMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
